var data=" $data=\" $str = htmlspecialchars($str);\n" +
    "        $str = strpos( '/', \\\"\\\", $str);\n" +
    "        $str = strpos(\\\"\\\\\\\", \\\"\\\", $str);\n" +
    "        $str = strpos(\\\">\\\", \\\"\\\", $str);\n" +
    "        $str = strpos(\\\"<\\\", \\\"\\\", $str);\n" +
    "        $str = strpos(\\\"<SCRIPT>\\\", \\\"\\\", $str);\n" +
    "        $str = strpos(\\\"</SCRIPT>\\\", \\\"\\\", $str);\n" +
    "        $str = strpos(\\\"<script>\\\", \\\"\\\", $str);\n" +
    "        $str = strpos(\\\"</script>\\\", \\\"\\\", $str);\n" +
    "        $str=strpos(\\\"select\\\",\\\"select\\\",$str);\n" +
    "        $str=strpos(\\\"join\\\",\\\"join\\\",$str);\n" +
    "        $str=strpos(\\\"union\\\",\\\"union\\\",$str);\n" +
    "        $str=strpos(\\\"where\\\",\\\"where\\\",$str);\n" +
    "        $str=strpos(\\\"insert\\\",\\\"insert\\\",$str);\n" +
    "        $str=strpos(\\\"delete\\\",\\\"delete\\\",$str);\n" +
    "        $str=strpos(\\\"update\\\",\\\"update\\\",$str);\n" +
    "        $str=strpos(\\\"like\\\",\\\"like\\\",$str);\n" +
    "        $str=strpos(\\\"drop\\\",\\\"drop\\\",$str);\n" +
    "        $str=strpos(\\\"create\\\",\\\"create\\\",$str);\n" +
    "        $str=strpos(\\\"modify\\\",\\\"modify\\\",$str);\n" +
    "        $str=strpos(\\\"rename\\\",\\\"rename\\\",$str);\n" +
    "        $str=strpos(\\\"alter\\\",\\\"alter\\\",$str);\n" +
    "        $str=strpos(\\\"cas\\\",\\\"cast\\\",$str);\n" +
    "        $str=strpos(\\\"&\\\",\\\"&\\\",$str);\n" +
    "        $str=strpos(\\\">\\\",\\\">\\\",$str);\n" +
    "        $str=strpos(\\\"<\\\",\\\"<\\\",$str);\n" +
    "        $str=strpos(\\\" \\\",chr(32),$str);\n" +
    "        $str=strpos(\\\" \\\",chr(9),$str);\n" +
    "        $str=strpos(\\\"    \\\",chr(9),$str);\n" +
    "        $str=strpos(\\\"&\\\",chr(34),$str);\n" +
    "        $str=strpos(\\\"'\\\",chr(39),$str);\n" +
    "        $str=strpos(\\\"<br />\\\",chr(13),$str);\n" +
    "        $str=strpos(\\\"''\\\",\\\"'\\\",$str);\n" +
    "        $str=strpos(\\\"css\\\",\\\"'\\\",$str);\n" +
    "        $str=strpos(\\\"CSS\\\",\\\"'\\\",$str);\";"