<?php
/**
 * Created by awesome.
 * Date: 2020-01-26 02:33:48
 */
namespace app\controller\native;
use app\controller\auth\auth_controller;
use app\controller\controller;
use app\Event\native_push_event;
use extend\awesome\awesome_echo_tool;
use request\request;
use task\rabbitmq;

class chat_controller extends controller
{
    public function construct()
    {
        parent::construct(); // TODO: Change the autogenerated stub
    }

    public function send_message(request $request,rabbitmq $rabbitmq){
//        return $request->all();
        awesome_echo_tool::safe_check($request);
//        $user_name=auth_controller::auth();
        $rules=[
            'msg'=>'reqiured|max:30',
        ];
        $request->verifacation($rules);
        $message=$request->all();
        $message['user_name']=auth_controller::auth();
        event(new native_push_event($message));
    }

    /**
     * 获取某个频道在线的人数
     * @param request $request
     * @param awesome_echo_tool $awesome_echo_tool
     * @return mixed
     */
    public function get_online_num(request $request,awesome_echo_tool $awesome_echo_tool){
        return $awesome_echo_tool->channel_online_count($request->get("channel_name"));
    }
    public function get_online_users_num(awesome_echo_tool $awesome_echo_tool){
        return count($awesome_echo_tool->get_online_users());
    }
}