---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2020/1/26 0026 下午 5:33
---
---
     local result=redis.call('hGet',KEYS[1],KEYS[2])
        local keys1={}
        if result==nil or result==false then
            local list={};
            list[ARGV[1]]={}
            list[ARGV[2]]=ARGV[3]
            return redis.call('hSet',KEYS[1],KEYS[2],cjson.encode(list));
        else
            result=cjson.decode(result)
            if result[ARGV[1]]==nil then


            return redis.call('hSet',KEYS[1],KEYS[2],cjson.encode(result));
        end